service: serverless-course-udemy

plugins:
  - serverless-bundle
  - serverless-lift
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  profile: personal
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - dynamodb:PutItem
          Resource:
            - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/auctions_table

resources:
  Resources:
    AuctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: auctions_table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
  
constructs:
  NewAuctionItemQueue:
    type: queue
    worker:
      handler: src/handlers/createAuction.handler
  
functions:
  newAuction:
    handler:  src/handlers/newAuction.handler
    environment:
      QUEUE_URL: ${construct:NewAuctionItemQueue.queueUrl}
    events:
      - http:
          method: POST
          path: auction
  dontClick:
    handler: src/handlers/dontClick.handler
    events:
      - http:
          method: GET
          path: /dont-click-this-link